language: rust
sudo: false

cache:
    - cargo

rust:
    - stable

# Following example from https://github.com/rust-lang/mdBook/blob/69a08ef390750d3cdbcdf807f505e559eb6418c6/book-example/src/continuous-integration.md
before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
  - cargo install-update -a

script:
  - mdbook build && mdbook test
